/* 자동 선택·뜻 찾기에 사용하는 단어 은행 (수준: 중학생 | 고등학생 | 대학생 | 최상위) */
const WORD_BANK = [
  // 중학생
  { word: "abandon", meanings: ["포기하다", "버리다"], level: "중학생" },
  { word: "ability", meanings: ["능력", "재능"], level: "중학생" },
  { word: "accept", meanings: ["받아들이다", "수락하다"], level: "중학생" },
  { word: "achieve", meanings: ["달성하다", "이루다"], level: "중학생" },
  { word: "active", meanings: ["활동적인", "적극적인"], level: "중학생" },
  { word: "advice", meanings: ["조언", "충고"], level: "중학생" },
  { word: "agree", meanings: ["동의하다", "찬성하다"], level: "중학생" },
  { word: "allow", meanings: ["허락하다", "허용하다"], level: "중학생" },
  { word: "appear", meanings: ["나타나다", "보이다"], level: "중학생" },
  { word: "arrive", meanings: ["도착하다", "이르다"], level: "중학생" },
  { word: "attend", meanings: ["참석하다", "출석하다"], level: "중학생" },
  { word: "avoid", meanings: ["피하다", "회피하다"], level: "중학생" },
  { word: "basic", meanings: ["기본적인", "기초의"], level: "중학생" },
  { word: "benefit", meanings: ["이익", "혜택"], level: "중학생" },
  { word: "borrow", meanings: ["빌리다", "차용하다"], level: "중학생" },
  { word: "brave", meanings: ["용감한", "용기 있는"], level: "중학생" },
  { word: "bright", meanings: ["밝은", "총명한"], level: "중학생" },
  { word: "careful", meanings: ["조심스러운", "신중한"], level: "중학생" },
  { word: "cause", meanings: ["원인", "일으키다"], level: "중학생" },
  { word: "chance", meanings: ["기회", "가능성"], level: "중학생" },
  { word: "choose", meanings: ["선택하다", "고르다"], level: "중학생" },
  { word: "common", meanings: ["흔한", "공통의"], level: "중학생" },
  { word: "compare", meanings: ["비교하다", "견주다"], level: "중학생" },
  { word: "complete", meanings: ["완성하다", "완전한"], level: "중학생" },
  { word: "consider", meanings: ["고려하다", "생각하다"], level: "중학생" },
  { word: "continue", meanings: ["계속하다", "이어지다"], level: "중학생" },
  { word: "create", meanings: ["만들다", "창조하다"], level: "중학생" },
  { word: "decide", meanings: ["결정하다", "결심하다"], level: "중학생" },
  { word: "describe", meanings: ["묘사하다", "설명하다"], level: "중학생" },
  { word: "develop", meanings: ["발전하다", "개발하다"], level: "중학생" },
  { word: "different", meanings: ["다른", "다양한"], level: "중학생" },
  { word: "discover", meanings: ["발견하다", "알아내다"], level: "중학생" },
  { word: "discuss", meanings: ["토론하다", "상의하다"], level: "중학생" },
  { word: "effort", meanings: ["노력", "수고"], level: "중학생" },
  { word: "enjoy", meanings: ["즐기다", "좋아하다"], level: "중학생" },
  { word: "enough", meanings: ["충분한", "충분히"], level: "중학생" },
  { word: "example", meanings: ["예", "본보기"], level: "중학생" },
  { word: "expect", meanings: ["기대하다", "예상하다"], level: "중학생" },
  { word: "explain", meanings: ["설명하다", "해명하다"], level: "중학생" },
  { word: "famous", meanings: ["유명한", "이름난"], level: "중학생" },
  { word: "follow", meanings: ["따르다", "따라가다"], level: "중학생" },
  { word: "foreign", meanings: ["외국의", "낯선"], level: "중학생" },
  { word: "forget", meanings: ["잊다", "깜빡하다"], level: "중학생" },
  { word: "future", meanings: ["미래", "장래"], level: "중학생" },
  { word: "gather", meanings: ["모으다", "모이다"], level: "중학생" },
  { word: "general", meanings: ["일반적인", "전반적인"], level: "중학생" },
  { word: "happen", meanings: ["일어나다", "발생하다"], level: "중학생" },
  { word: "honest", meanings: ["정직한", "솔직한"], level: "중학생" },
  { word: "include", meanings: ["포함하다", "넣다"], level: "중학생" },
  { word: "increase", meanings: ["증가하다", "늘리다"], level: "중학생" },
  { word: "invite", meanings: ["초대하다", "권하다"], level: "중학생" },
  { word: "journey", meanings: ["여행", "여정"], level: "중학생" },
  { word: "knowledge", meanings: ["지식", "아는 것"], level: "중학생" },
  { word: "language", meanings: ["언어", "말"], level: "중학생" },
  { word: "listen", meanings: ["듣다", "귀를 기울이다"], level: "중학생" },
  { word: "manage", meanings: ["관리하다", "해내다"], level: "중학생" },
  { word: "memory", meanings: ["기억", "추억"], level: "중학생" },
  { word: "modern", meanings: ["현대의", "최신의"], level: "중학생" },
  { word: "nature", meanings: ["자연", "본성"], level: "중학생" },
  { word: "notice", meanings: ["알아차리다", "공지"], level: "중학생" },
  { word: "opinion", meanings: ["의견", "견해"], level: "중학생" },
  { word: "patient", meanings: ["참을성 있는", "환자"], level: "중학생" },
  { word: "perfect", meanings: ["완벽한", "완전한"], level: "중학생" },
  { word: "popular", meanings: ["인기 있는", "대중적인"], level: "중학생" },
  { word: "prepare", meanings: ["준비하다", "대비하다"], level: "중학생" },
  { word: "protect", meanings: ["보호하다", "지키다"], level: "중학생" },
  { word: "purpose", meanings: ["목적", "의도"], level: "중학생" },
  { word: "quality", meanings: ["질", "품질"], level: "중학생" },
  { word: "realize", meanings: ["깨닫다", "실현하다"], level: "중학생" },
  { word: "receive", meanings: ["받다", "수령하다"], level: "중학생" },
  { word: "remember", meanings: ["기억하다", "생각해 내다"], level: "중학생" },
  { word: "require", meanings: ["필요로 하다", "요구하다"], level: "중학생" },
  { word: "result", meanings: ["결과", "성과"], level: "중학생" },
  { word: "return", meanings: ["돌아오다", "반환하다"], level: "중학생" },
  { word: "science", meanings: ["과학", "학문"], level: "중학생" },
  { word: "search", meanings: ["찾다", "검색"], level: "중학생" },
  { word: "similar", meanings: ["비슷한", "유사한"], level: "중학생" },
  { word: "society", meanings: ["사회", "협회"], level: "중학생" },
  { word: "success", meanings: ["성공", "성취"], level: "중학생" },
  { word: "suggest", meanings: ["제안하다", "시사하다"], level: "중학생" },
  { word: "support", meanings: ["지지하다", "지원"], level: "중학생" },
  { word: "surprise", meanings: ["놀라게 하다", "놀람"], level: "중학생" },
  { word: "travel", meanings: ["여행하다", "이동하다"], level: "중학생" },
  { word: "various", meanings: ["다양한", "여러 가지의"], level: "중학생" },

  // 고등학생
  { word: "accurate", meanings: ["정확한", "정밀한"], level: "고등학생" },
  { word: "acquire", meanings: ["얻다", "습득하다"], level: "고등학생" },
  { word: "adequate", meanings: ["적절한", "충분한"], level: "고등학생" },
  { word: "advocate", meanings: ["옹호하다", "지지자"], level: "고등학생" },
  { word: "analyze", meanings: ["분석하다", "해석하다"], level: "고등학생" },
  { word: "approach", meanings: ["접근하다", "방법"], level: "고등학생" },
  { word: "assume", meanings: ["가정하다", "추정하다"], level: "고등학생" },
  { word: "attitude", meanings: ["태도", "자세"], level: "고등학생" },
  { word: "aware", meanings: ["알고 있는", "인식하는"], level: "고등학생" },
  { word: "challenge", meanings: ["도전", "이의를 제기하다"], level: "고등학생" },
  { word: "circumstance", meanings: ["상황", "환경"], level: "고등학생" },
  { word: "complex", meanings: ["복잡한", "복합적인"], level: "고등학생" },
  { word: "conclude", meanings: ["결론짓다", "끝내다"], level: "고등학생" },
  { word: "conduct", meanings: ["수행하다", "행동"], level: "고등학생" },
  { word: "consequence", meanings: ["결과", "영향"], level: "고등학생" },
  { word: "contribute", meanings: ["기여하다", "공헌하다"], level: "고등학생" },
  { word: "convince", meanings: ["설득하다", "납득시키다"], level: "고등학생" },
  { word: "critical", meanings: ["비판적인", "중요한"], level: "고등학생" },
  { word: "decline", meanings: ["거절하다", "감소하다"], level: "고등학생" },
  { word: "demonstrate", meanings: ["입증하다", "시연하다"], level: "고등학생" },
  { word: "determine", meanings: ["결정하다", "밝히다"], level: "고등학생" },
  { word: "diligent", meanings: ["부지런한", "성실한"], level: "고등학생" },
  { word: "distinct", meanings: ["뚜렷한", "구별되는"], level: "고등학생" },
  { word: "efficient", meanings: ["효율적인", "능률적인"], level: "고등학생" },
  { word: "eliminate", meanings: ["제거하다", "없애다"], level: "고등학생" },
  { word: "emphasize", meanings: ["강조하다", "역설하다"], level: "고등학생" },
  { word: "establish", meanings: ["설립하다", "확립하다"], level: "고등학생" },
  { word: "evaluate", meanings: ["평가하다", "감정하다"], level: "고등학생" },
  { word: "evidence", meanings: ["증거", "근거"], level: "고등학생" },
  { word: "expand", meanings: ["확장하다", "확대하다"], level: "고등학생" },
  { word: "expose", meanings: ["노출시키다", "폭로하다"], level: "고등학생" },
  { word: "factor", meanings: ["요인", "요소"], level: "고등학생" },
  { word: "feature", meanings: ["특징", "특집"], level: "고등학생" },
  { word: "frequent", meanings: ["빈번한", "자주 일어나는"], level: "고등학생" },
  { word: "generate", meanings: ["생성하다", "발생시키다"], level: "고등학생" },
  { word: "hesitate", meanings: ["망설이다", "주저하다"], level: "고등학생" },
  { word: "identify", meanings: ["확인하다", "식별하다"], level: "고등학생" },
  { word: "illustrate", meanings: ["설명하다", "예시하다"], level: "고등학생" },
  { word: "impact", meanings: ["영향", "충격"], level: "고등학생" },
  { word: "indicate", meanings: ["나타내다", "가리키다"], level: "고등학생" },
  { word: "influence", meanings: ["영향", "영향을 미치다"], level: "고등학생" },
  { word: "interpret", meanings: ["해석하다", "통역하다"], level: "고등학생" },
  { word: "involve", meanings: ["관련시키다", "포함하다"], level: "고등학생" },
  { word: "justify", meanings: ["정당화하다", "옳음을 증명하다"], level: "고등학생" },
  { word: "maintain", meanings: ["유지하다", "보수하다"], level: "고등학생" },
  { word: "major", meanings: ["주요한", "전공"], level: "고등학생" },
  { word: "method", meanings: ["방법", "방식"], level: "고등학생" },
  { word: "obtain", meanings: ["얻다", "획득하다"], level: "고등학생" },
  { word: "occur", meanings: ["발생하다", "일어나다"], level: "고등학생" },
  { word: "outcome", meanings: ["결과", "성과"], level: "고등학생" },
  { word: "perceive", meanings: ["인식하다", "감지하다"], level: "고등학생" },
  { word: "persist", meanings: ["지속하다", "고집하다"], level: "고등학생" },
  { word: "potential", meanings: ["잠재적인", "가능성"], level: "고등학생" },
  { word: "previous", meanings: ["이전의", "앞선"], level: "고등학생" },
  { word: "primary", meanings: ["주요한", "일차적인"], level: "고등학생" },
  { word: "principle", meanings: ["원칙", "원리"], level: "고등학생" },
  { word: "process", meanings: ["과정", "처리하다"], level: "고등학생" },
  { word: "promote", meanings: ["촉진하다", "승진시키다"], level: "고등학생" },
  { word: "propose", meanings: ["제안하다", "제의하다"], level: "고등학생" },
  { word: "range", meanings: ["범위", "다양하다"], level: "고등학생" },
  { word: "reduce", meanings: ["줄이다", "감소시키다"], level: "고등학생" },
  { word: "reflect", meanings: ["반영하다", "숙고하다"], level: "고등학생" },
  { word: "relevant", meanings: ["관련 있는", "적절한"], level: "고등학생" },
  { word: "rely", meanings: ["의존하다", "믿다"], level: "고등학생" },
  { word: "represent", meanings: ["나타내다", "대표하다"], level: "고등학생" },
  { word: "respond", meanings: ["응답하다", "대응하다"], level: "고등학생" },
  { word: "reveal", meanings: ["드러내다", "밝히다"], level: "고등학생" },
  { word: "significant", meanings: ["중요한", "의미 있는"], level: "고등학생" },
  { word: "source", meanings: ["출처", "원천"], level: "고등학생" },
  { word: "specific", meanings: ["구체적인", "특정한"], level: "고등학생" },
  { word: "structure", meanings: ["구조", "구성하다"], level: "고등학생" },
  { word: "sufficient", meanings: ["충분한", "족한"], level: "고등학생" },
  { word: "theory", meanings: ["이론", "학설"], level: "고등학생" },
  { word: "transfer", meanings: ["옮기다", "이전"], level: "고등학생" },
  { word: "vary", meanings: ["다르다", "변화하다"], level: "고등학생" },

  // 대학생
  { word: "abstract", meanings: ["추상적인", "요약"], level: "대학생" },
  { word: "accommodate", meanings: ["수용하다", "적응하다"], level: "대학생" },
  { word: "accumulate", meanings: ["축적하다", "모으다"], level: "대학생" },
  { word: "acknowledge", meanings: ["인정하다", "감사하다"], level: "대학생" },
  { word: "allocate", meanings: ["할당하다", "배분하다"], level: "대학생" },
  { word: "ambiguous", meanings: ["모호한", "애매한"], level: "대학생" },
  { word: "anticipate", meanings: ["예상하다", "기대하다"], level: "대학생" },
  { word: "arbitrary", meanings: ["임의의", "독단적인"], level: "대학생" },
  { word: "assess", meanings: ["평가하다", "산정하다"], level: "대학생" },
  { word: "attribute", meanings: ["속성", "기인하다"], level: "대학생" },
  { word: "coherent", meanings: ["일관성 있는", "논리적인"], level: "대학생" },
  { word: "coincide", meanings: ["일치하다", "동시에 일어나다"], level: "대학생" },
  { word: "compile", meanings: ["편집하다", "모으다"], level: "대학생" },
  { word: "comprehensive", meanings: ["포괄적인", "종합적인"], level: "대학생" },
  { word: "conceive", meanings: ["생각하다", "임신하다"], level: "대학생" },
  { word: "concurrent", meanings: ["동시 발생의", "병행하는"], level: "대학생" },
  { word: "confine", meanings: ["국한하다", "가두다"], level: "대학생" },
  { word: "consensus", meanings: ["합의", "여론"], level: "대학생" },
  { word: "constrain", meanings: ["제약하다", "강제하다"], level: "대학생" },
  { word: "contemplate", meanings: ["숙고하다", "명상하다"], level: "대학생" },
  { word: "contradict", meanings: ["모순되다", "반박하다"], level: "대학생" },
  { word: "criterion", meanings: ["기준", "표준"], level: "대학생" },
  { word: "crucial", meanings: ["결정적인", "중대한"], level: "대학생" },
  { word: "derive", meanings: ["도출하다", "유래하다"], level: "대학생" },
  { word: "diminish", meanings: ["줄어들다", "약화시키다"], level: "대학생" },
  { word: "discrete", meanings: ["별개의", "분리된"], level: "대학생" },
  { word: "displace", meanings: ["대체하다", "쫓아내다"], level: "대학생" },
  { word: "diverse", meanings: ["다양한", "이질적인"], level: "대학생" },
  { word: "domain", meanings: ["영역", "분야"], level: "대학생" },
  { word: "elaborate", meanings: ["정교한", "자세히 설명하다"], level: "대학생" },
  { word: "emerge", meanings: ["나타나다", "부상하다"], level: "대학생" },
  { word: "enhance", meanings: ["향상시키다", "강화하다"], level: "대학생" },
  { word: "ensure", meanings: ["보장하다", "확실히 하다"], level: "대학생" },
  { word: "essential", meanings: ["필수적인", "본질적인"], level: "대학생" },
  { word: "exploit", meanings: ["이용하다", "착취하다"], level: "대학생" },
  { word: "facilitate", meanings: ["용이하게 하다", "촉진하다"], level: "대학생" },
  { word: "fluctuate", meanings: ["변동하다", "오르내리다"], level: "대학생" },
  { word: "formulate", meanings: ["공식화하다", "만들어 내다"], level: "대학생" },
  { word: "framework", meanings: ["틀", "체계"], level: "대학생" },
  { word: "hypothesis", meanings: ["가설", "가정"], level: "대학생" },
  { word: "imply", meanings: ["암시하다", "내포하다"], level: "대학생" },
  { word: "incentive", meanings: ["동기", "장려책"], level: "대학생" },
  { word: "inherent", meanings: ["고유한", "내재하는"], level: "대학생" },
  { word: "integrate", meanings: ["통합하다", "융합하다"], level: "대학생" },
  { word: "integrity", meanings: ["진실성", "완전성"], level: "대학생" },
  { word: "intervene", meanings: ["개입하다", "중재하다"], level: "대학생" },
  { word: "intrinsic", meanings: ["본질적인", "고유의"], level: "대학생" },
  { word: "legitimate", meanings: ["합법적인", "정당한"], level: "대학생" },
  { word: "manipulate", meanings: ["조작하다", "다루다"], level: "대학생" },
  { word: "notion", meanings: ["개념", "생각"], level: "대학생" },
  { word: "objective", meanings: ["목표", "객관적인"], level: "대학생" },
  { word: "perspective", meanings: ["관점", "시각"], level: "대학생" },
  { word: "phenomenon", meanings: ["현상", "경이"], level: "대학생" },
  { word: "precise", meanings: ["정확한", "정밀한"], level: "대학생" },
  { word: "predominant", meanings: ["우세한", "지배적인"], level: "대학생" },
  { word: "preliminary", meanings: ["예비의", "사전적인"], level: "대학생" },
  { word: "presume", meanings: ["추정하다", "가정하다"], level: "대학생" },
  { word: "priority", meanings: ["우선순위", "중요도"], level: "대학생" },
  { word: "proportion", meanings: ["비율", "부분"], level: "대학생" },
  { word: "prospect", meanings: ["전망", "가능성"], level: "대학생" },
  { word: "protocol", meanings: ["의정서", "규약"], level: "대학생" },
  { word: "rational", meanings: ["합리적인", "이성적인"], level: "대학생" },
  { word: "refine", meanings: ["정제하다", "개선하다"], level: "대학생" },
  { word: "reinforce", meanings: ["강화하다", "보강하다"], level: "대학생" },
  { word: "reluctant", meanings: ["꺼리는", "마지못한"], level: "대학생" },
  { word: "resolve", meanings: ["해결하다", "결심하다"], level: "대학생" },
  { word: "restrict", meanings: ["제한하다", "한정하다"], level: "대학생" },
  { word: "retain", meanings: ["유지하다", "보유하다"], level: "대학생" },
  { word: "rigid", meanings: ["경직된", "엄격한"], level: "대학생" },
  { word: "simulate", meanings: ["모의하다", "흉내 내다"], level: "대학생" },
  { word: "speculate", meanings: ["추측하다", "투기하다"], level: "대학생" },
  { word: "subsequent", meanings: ["그 다음의", "이후의"], level: "대학생" },
  { word: "sustain", meanings: ["유지하다", "지속하다"], level: "대학생" },
  { word: "thesis", meanings: ["논문", "논제"], level: "대학생" },
  { word: "undergo", meanings: ["겪다", "받다"], level: "대학생" },
  { word: "undertake", meanings: ["착수하다", "맡다"], level: "대학생" },
  { word: "valid", meanings: ["유효한", "타당한"], level: "대학생" },
  { word: "violate", meanings: ["위반하다", "침해하다"], level: "대학생" },

  // 최상위
  { word: "aberration", meanings: ["일탈", "이상"], level: "최상위" },
  { word: "abrogate", meanings: ["폐지하다", "무효로 하다"], level: "최상위" },
  { word: "acerbic", meanings: ["신랄한", "쓴"], level: "최상위" },
  { word: "alacrity", meanings: ["민첩함", "기민함"], level: "최상위" },
  { word: "anachronism", meanings: ["시대착오", "시대에 맞지 않는 것"], level: "최상위" },
  { word: "apocryphal", meanings: ["출처가 불분명한", "위작의"], level: "최상위" },
  { word: "assiduous", meanings: ["근면한", "꾸준한"], level: "최상위" },
  { word: "belligerent", meanings: ["호전적인", "교전 중인"], level: "최상위" },
  { word: "cacophony", meanings: ["불협화음", "소음"], level: "최상위" },
  { word: "capricious", meanings: ["변덕스러운", "예측 불가능한"], level: "최상위" },
  { word: "circumspect", meanings: ["신중한", "조심스러운"], level: "최상위" },
  { word: "conundrum", meanings: ["난제", "수수께끼"], level: "최상위" },
  { word: "deleterious", meanings: ["해로운", "유해한"], level: "최상위" },
  { word: "diaphanous", meanings: ["비치는", "얇은"], level: "최상위" },
  { word: "ebullient", meanings: ["열광적인", "넘치는"], level: "최상위" },
  { word: "ephemeral", meanings: ["덧없는", "일시적인"], level: "최상위" },
  { word: "equivocal", meanings: ["애매한", "모호한"], level: "최상위" },
  { word: "esoteric", meanings: ["난해한", "소수만 아는"], level: "최상위" },
  { word: "exacerbate", meanings: ["악화시키다", "심화시키다"], level: "최상위" },
  { word: "fastidious", meanings: ["까다로운", "세심한"], level: "최상위" },
  { word: "gregarious", meanings: ["사교적인", "무리 짓는"], level: "최상위" },
  { word: "harangue", meanings: ["장광설", "열변을 토하다"], level: "최상위" },
  { word: "iconoclast", meanings: ["기존 관념을 깨는 사람", "우상 파괴자"], level: "최상위" },
  { word: "idiosyncrasy", meanings: ["특이성", "개성"], level: "최상위" },
  { word: "impecunious", meanings: ["무일푼의", "가난한"], level: "최상위" },
  { word: "inchoate", meanings: ["초기 단계의", "미완성의"], level: "최상위" },
  { word: "ineffable", meanings: ["형언할 수 없는", "말로 다할 수 없는"], level: "최상위" },
  { word: "insidious", meanings: ["교활한", "잠행성의"], level: "최상위" },
  { word: "intransigent", meanings: ["비타협적인", "완고한"], level: "최상위" },
  { word: "laconic", meanings: ["간결한", "말수가 적은"], level: "최상위" },
  { word: "lugubrious", meanings: ["침울한", "애처로운"], level: "최상위" },
  { word: "mellifluous", meanings: ["감미로운", "유창한"], level: "최상위" },
  { word: "obfuscate", meanings: ["혼란스럽게 하다", "애매하게 하다"], level: "최상위" },
  { word: "obstreperous", meanings: ["시끄러운", "다루기 힘든"], level: "최상위" },
  { word: "ostentatious", meanings: ["과시적인", "허세 부리는"], level: "최상위" },
  { word: "paradigm", meanings: ["패러다임", "전형"], level: "최상위" },
  { word: "perfidious", meanings: ["배신적인", "불성실한"], level: "최상위" },
  { word: "perspicacious", meanings: ["통찰력 있는", "명민한"], level: "최상위" },
  { word: "phlegmatic", meanings: ["냉정한", "무관심한"], level: "최상위" },
  { word: "proclivity", meanings: ["성향", "기질"], level: "최상위" },
  { word: "prosaic", meanings: ["평범한", "산문적인"], level: "최상위" },
  { word: "quixotic", meanings: ["비현실적인", "공상적인"], level: "최상위" },
  { word: "recalcitrant", meanings: ["다루기 힘든", "반항적인"], level: "최상위" },
  { word: "recondite", meanings: ["난해한", "심오한"], level: "최상위" },
  { word: "sagacious", meanings: ["현명한", "통찰력 있는"], level: "최상위" },
  { word: "sanguine", meanings: ["낙관적인", "혈색이 좋은"], level: "최상위" },
  { word: "sycophant", meanings: ["아첨꾼", "아부하는 사람"], level: "최상위" },
  { word: "taciturn", meanings: ["과묵한", "말수가 적은"], level: "최상위" },
  { word: "ubiquitous", meanings: ["어디에나 있는", "보편적인"], level: "최상위" },
  { word: "vacillate", meanings: ["동요하다", "망설이다"], level: "최상위" },
  { word: "venerable", meanings: ["존경할 만한", "유서 깊은"], level: "최상위" },
  { word: "vitriolic", meanings: ["신랄한", "독설의"], level: "최상위" },
  { word: "zealous", meanings: ["열성적인", "열렬한"], level: "최상위" },
];
